"""Fix user role column

Revision ID: 8457d4e40c61
Revises: 001_create_orders_table
Create Date: 2026-05-01 00:30:41.567391

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8457d4e40c61'
down_revision: Union[str, None] = '001_create_orders_table'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('example')
    op.drop_index('ix_restaurants_id', table_name='restaurants')
    op.drop_table('restaurants')
    # Keep restaurant_profiles.id as UUID - no conversion needed
    op.alter_column('restaurant_profiles', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('restaurant_profiles', 'restaurant_name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('restaurant_profiles', 'status',
               existing_type=postgresql.ENUM('pending', 'approved', 'rejected', name='restaurant_status'),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text("'pending'::restaurant_status"))
    op.drop_constraint('unique_user_restaurant', 'restaurant_profiles', type_='unique', cascade=True)
    op.create_index(op.f('ix_restaurant_profiles_id'), 'restaurant_profiles', ['id'], unique=False)
    op.drop_constraint('restaurant_profiles_user_id_fkey', 'restaurant_profiles', type_='foreignkey')
    op.create_foreign_key(None, 'restaurant_profiles', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'restaurant_profiles', 'users', ['approved_by'], ['id'])
    op.alter_column('users', 'firebase_uid',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('users', 'phone',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('users', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('users', 'photo_url',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('user', 'admin', 'restaurant_owner', name='user_role'),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text("'user'::user_role"))
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.drop_constraint('users_phone_key', 'users', type_='unique')
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'updated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
    op.create_unique_constraint('users_phone_key', 'users', ['phone'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint('users_email_key', 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.alter_column('users', 'role',
               existing_type=sa.String(),
               type_=postgresql.ENUM('user', 'admin', 'restaurant_owner', name='user_role'),
               existing_nullable=True,
               existing_server_default=sa.text("'user'::user_role"))
    op.alter_column('users', 'photo_url',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('users', 'name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('users', 'phone',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('users', 'firebase_uid',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_constraint(None, 'restaurant_profiles', type_='foreignkey')
    op.drop_constraint(None, 'restaurant_profiles', type_='foreignkey')
    op.create_foreign_key('restaurant_profiles_user_id_fkey', 'restaurant_profiles', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_restaurant_profiles_id'), table_name='restaurant_profiles')
    op.create_unique_constraint('unique_user_restaurant', 'restaurant_profiles', ['user_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('restaurant_profiles', 'status',
               existing_type=sa.String(),
               type_=postgresql.ENUM('pending', 'approved', 'rejected', name='restaurant_status'),
               existing_nullable=True,
               existing_server_default=sa.text("'pending'::restaurant_status"))
    op.alter_column('restaurant_profiles', 'restaurant_name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('restaurant_profiles', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    # Keep restaurant_profiles.id as UUID - no conversion needed
    op.create_table('restaurants',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('owner_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('address', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('city', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('cuisine_types', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('fssai_license', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name='restaurants_owner_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='restaurants_pkey')
    )
    op.create_index('ix_restaurants_id', 'restaurants', ['id'], unique=False)
    op.create_table('example',
    sa.Column('status', postgresql.ENUM('pending', 'approved', 'rejected', name='restaurant_status'), server_default=sa.text("'pending'::restaurant_status"), autoincrement=False, nullable=False)
    )
    # ### end Alembic commands ###
