"""Upgrade orders architecture with order_items and tracking

Revision ID: 93fb96c7f863
Revises: a19115cbcc1f
Create Date: 2026-05-08 11:42:36.218235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '93fb96c7f863'
down_revision: Union[str, None] = 'a19115cbcc1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add new columns to orders table
    op.add_column('orders', sa.Column('order_number', sa.String(length=50), nullable=False))
    op.add_column('orders', sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('orders', sa.Column('tax_amount', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('orders', sa.Column('delivery_fee', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('orders', sa.Column('payment_method', sa.String(length=50), nullable=True))
    op.add_column('orders', sa.Column('payment_status', sa.String(length=50), nullable=True))
    op.add_column('orders', sa.Column('order_status', sa.String(length=50), nullable=True))
    op.add_column('orders', sa.Column('delivery_address', sa.Text(), nullable=True))
    op.add_column('orders', sa.Column('customer_lat', sa.Numeric(precision=10, scale=8), nullable=True))
    op.add_column('orders', sa.Column('customer_lng', sa.Numeric(precision=11, scale=8), nullable=True))
    op.add_column('orders', sa.Column('estimated_delivery_time', sa.String(length=50), nullable=True))
    op.add_column('orders', sa.Column('updated_at', sa.DateTime(), nullable=True))
    
    # Create unique constraint for order_number
    op.create_unique_constraint('uq_orders_order_number', 'orders', ['order_number'])
    
    # Update foreign key to reference restaurant_profiles.id instead of user_id
    op.drop_constraint('orders_restaurant_id_fkey', 'orders', type_='foreignkey')
    op.create_foreign_key('fk_orders_restaurant_id', 'orders', 'restaurant_profiles', ['restaurant_id'], ['id'])
    
    # Create order_items table
    op.create_table('order_items',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('order_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('menu_item_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('item_name', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['menu_item_id'], ['menu_items.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    
    # Create order_tracking_logs table
    op.create_table('order_tracking_logs',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('order_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # Remove old status column as we now have order_status
    op.drop_column('orders', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop order_tracking_logs table
    op.drop_table('order_tracking_logs')
    
    # Drop order_items table
    op.drop_table('order_items')
    
    # Drop new columns from orders table
    op.drop_constraint('uq_orders_order_number', 'orders', type_='unique')
    op.drop_column('orders', 'updated_at')
    op.drop_column('orders', 'estimated_delivery_time')
    op.drop_column('orders', 'customer_lng')
    op.drop_column('orders', 'customer_lat')
    op.drop_column('orders', 'delivery_address')
    op.drop_column('orders', 'order_status')
    op.drop_column('orders', 'payment_status')
    op.drop_column('orders', 'payment_method')
    op.drop_column('orders', 'delivery_fee')
    op.drop_column('orders', 'tax_amount')
    op.drop_column('orders', 'subtotal')
    op.drop_column('orders', 'order_number')
    
    # Restore original foreign key
    op.drop_constraint('fk_orders_restaurant_id', 'orders', type_='foreignkey')
    op.create_foreign_key('orders_restaurant_id_fkey', 'orders', 'restaurant_profiles', ['restaurant_id'], ['user_id'])
    # ### end Alembic commands ###
