"""Placeholder between orders upgrade and payments table

Revision ID: eabcd7782b04
Revises: 93fb96c7f863
Create Date: 2026-05-08 12:37:27.303011

An earlier version of this file contained autogenerated DDL (including
``restaurant_profiles.id`` UUID -> INTEGER) that PostgreSQL cannot apply and
that does not match this app's UUID-based ``restaurant_profiles.id`` /
``orders.restaurant_id`` schema. That block was removed. The ``payments`` table
is created in revision ``create_payments_table``.
"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = 'eabcd7782b04'
down_revision: Union[str, None] = '93fb96c7f863'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    pass


def downgrade() -> None:
    pass
