"""create payments table

Revision ID: eabcd7782b04
Revises: 93fb96c7f863
Create Date: 2026-05-08 12:37:27.303011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'eabcd7782b04'
down_revision: Union[str, None] = '93fb96c7f863'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_restaurants_id', table_name='restaurants')
    op.drop_table('restaurants')
    op.drop_table('example')
    op.alter_column('menu_categories', 'restaurant_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('menu_items', 'restaurant_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('menu_items', 'category_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.add_column('orders', sa.Column('order_number', sa.String(length=50), nullable=False))
    op.add_column('orders', sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('orders', sa.Column('tax_amount', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('orders', sa.Column('delivery_fee', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('orders', sa.Column('payment_method', sa.String(length=50), nullable=True))
    op.add_column('orders', sa.Column('payment_status', sa.String(length=50), nullable=True))
    op.add_column('orders', sa.Column('order_status', sa.String(length=50), nullable=True))
    op.add_column('orders', sa.Column('delivery_address', sa.Text(), nullable=True))
    op.add_column('orders', sa.Column('customer_lat', sa.Numeric(precision=10, scale=8), nullable=True))
    op.add_column('orders', sa.Column('customer_lng', sa.Numeric(precision=11, scale=8), nullable=True))
    op.add_column('orders', sa.Column('estimated_delivery_time', sa.String(length=50), nullable=True))
    op.add_column('orders', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.create_unique_constraint(None, 'orders', ['order_number'])
    op.drop_constraint('orders_restaurant_id_fkey', 'orders', type_='foreignkey')
    op.create_foreign_key(None, 'orders', 'restaurant_profiles', ['restaurant_id'], ['id'])
    op.drop_column('orders', 'status')
    op.alter_column('restaurant_profiles', 'id',
               existing_type=sa.UUID(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text('gen_random_uuid()'))
    op.alter_column('restaurant_profiles', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('restaurant_profiles', 'restaurant_name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('restaurant_profiles', 'status',
               existing_type=postgresql.ENUM('pending', 'approved', 'rejected', name='restaurant_status'),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text("'pending'::restaurant_status"))
    op.drop_constraint('unique_user_restaurant', 'restaurant_profiles', type_='unique')
    op.create_index(op.f('ix_restaurant_profiles_id'), 'restaurant_profiles', ['id'], unique=False)
    op.drop_constraint('restaurant_profiles_user_id_fkey', 'restaurant_profiles', type_='foreignkey')
    op.create_foreign_key(None, 'restaurant_profiles', 'users', ['approved_by'], ['id'])
    op.create_foreign_key(None, 'restaurant_profiles', 'users', ['user_id'], ['id'])
    op.alter_column('users', 'firebase_uid',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('users', 'phone',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('users', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('users', 'photo_url',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('user', 'admin', 'restaurant_owner', name='user_role'),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text("'user'::user_role"))
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.drop_constraint('users_phone_key', 'users', type_='unique')
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'updated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
    op.create_unique_constraint('users_phone_key', 'users', ['phone'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint('users_email_key', 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.alter_column('users', 'role',
               existing_type=sa.String(),
               type_=postgresql.ENUM('user', 'admin', 'restaurant_owner', name='user_role'),
               existing_nullable=True,
               existing_server_default=sa.text("'user'::user_role"))
    op.alter_column('users', 'photo_url',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('users', 'name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('users', 'phone',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('users', 'firebase_uid',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_constraint(None, 'restaurant_profiles', type_='foreignkey')
    op.drop_constraint(None, 'restaurant_profiles', type_='foreignkey')
    op.create_foreign_key('restaurant_profiles_user_id_fkey', 'restaurant_profiles', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_restaurant_profiles_id'), table_name='restaurant_profiles')
    op.create_unique_constraint('unique_user_restaurant', 'restaurant_profiles', ['user_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('restaurant_profiles', 'status',
               existing_type=sa.String(),
               type_=postgresql.ENUM('pending', 'approved', 'rejected', name='restaurant_status'),
               existing_nullable=True,
               existing_server_default=sa.text("'pending'::restaurant_status"))
    op.alter_column('restaurant_profiles', 'restaurant_name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('restaurant_profiles', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('restaurant_profiles', 'id',
               existing_type=sa.Integer(),
               type_=sa.UUID(),
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text('gen_random_uuid()'))
    op.add_column('orders', sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.create_foreign_key('orders_restaurant_id_fkey', 'orders', 'restaurant_profiles', ['restaurant_id'], ['user_id'])
    op.drop_constraint(None, 'orders', type_='unique')
    op.drop_column('orders', 'updated_at')
    op.drop_column('orders', 'estimated_delivery_time')
    op.drop_column('orders', 'customer_lng')
    op.drop_column('orders', 'customer_lat')
    op.drop_column('orders', 'delivery_address')
    op.drop_column('orders', 'order_status')
    op.drop_column('orders', 'payment_status')
    op.drop_column('orders', 'payment_method')
    op.drop_column('orders', 'delivery_fee')
    op.drop_column('orders', 'tax_amount')
    op.drop_column('orders', 'subtotal')
    op.drop_column('orders', 'order_number')
    op.alter_column('menu_items', 'category_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('menu_items', 'restaurant_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('menu_categories', 'restaurant_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_table('example',
    sa.Column('status', postgresql.ENUM('pending', 'approved', 'rejected', name='restaurant_status'), server_default=sa.text("'pending'::restaurant_status"), autoincrement=False, nullable=False)
    )
    op.create_table('restaurants',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('owner_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('address', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('city', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('cuisine_types', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('fssai_license', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name='restaurants_owner_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='restaurants_pkey')
    )
    op.create_index('ix_restaurants_id', 'restaurants', ['id'], unique=False)
    # ### end Alembic commands ###
